defaultPage:
    description: >-
      Where sleek design meets penguin power.
      Dive into creative solutions for your website.
      Join the penguin revolution!
    css:
      - css/main.css
    js:
      - https://unpkg.com/@unseenco/e@2.4.0/dist/e.umd.js
      - https://unpkg.com/@unseenco/taxi@1.5.2/dist/taxi.umd.js
      - js/main.js
    gfonts:
      - Ubuntu:ital,wght@0,400;0,700;1,300

pages:
  index:
    title: Home | Gentoo Web Development
  
  services:
    title: Services | Gentoo Web Development
  
  portfolio:
    title: Portfolio | Gentoo Web Development
  
  contact:
    title: Contact | Gentoo Web Development